---
# file: roles/setup_docker/tasks/main.yml
# Dockerのインストール
# python: version3 *依存関係等注意して開発すること。

# Docker
- name: add docker gpg key #docker公式のGPG公開鍵をインストール
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository #aptリポジトリの設定
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: install docker-ce # dockerの無償版をインストール(Community Edition)
  apt:
    name: docker-ce
    state: present
    update_cache: yes

# pip
- name: install pip3 # pipのインストール
  apt:
    name: "python3-pip"

- name: install python-apt # --check用パッケージのインストール
  apt:
    name: python-apt
    state: latest

- name: pip install docker # dockerを使うのに用いるパッケージ
  pip:
    name: docker
