---
# file: roles/setup_k3s/tasks/main.yml
# k3sの設定ファイル（deployment, service）のコピーとdeployするイメージの作成

# copy files
- name: copy files
  copy:
    src: files/
    dest: "{{ dockerfile_path }}"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

# build docker_image
- name: build nginx
  docker_image:
    build:
      path: "{{ dockerfile_path }}"
      pull: yes
    name: example/nginx
    source: build
  vars:
    ansible_python_interpreter: /usr/bin/python3

# push docker_image to a local repo
- name: push an image to a local repo
  docker_image:
    name: example/nginx
    repository: localhost:5000/nginx
    push: yes
    source: local
  vars:
    ansible_python_interpreter: /usr/bin/python3

# k3s内の環境自動設定（途中）
# # pip
# - name: install pip3 # pipのインストール
#   apt:
#     name: "python3-pip"

# # k8sを操作するためのパッケージ
# - name: install pip
#   pip:
#     name: openshift
#   vars:
#         ansible_python_interpreter: /usr/bin/python3

# - name: Create a Service object from a file
#   k8s:
#     state: present
#     src: ./files/service.yml

# - name: Create a Service object from a file
#   k8s:
#     state: present
#     src: ./files/deployment.yml
