---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: download }

- hosts: master
#  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master }
    - { role: setup_docker }
    - { role: setup_registry }
    - { role: setup_k3s }

- hosts: worker
#  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node }

- hosts: rancher
  become: yes
  roles:
    - { role: setup_docker }
    - { role: setup_rancher }
